# Generated by Django 2.1 on 2018-08-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('PD', 'Pending'), ('CP', 'Complete'), ('FD', 'Failed')], max_length=2)),
                ('task_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UnfollowNonFollowersTask',
            fields=[
                ('bottask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_tasks.BotTask')),
            ],
            bases=('bot_tasks.bottask',),
        ),
        migrations.AddField(
            model_name='bottask',
            name='twitter_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_accounts.TwitterAccount'),
        ),
    ]
